### ISSUE TITLE
数选字词无法顶屏

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#10]
飞讯快顶增强时数选字词无法顶屏，慢顶可以。飞码增强时，数选单字不能顶。简码增强时，数选字词不能顶。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/0d554e9e9693d28f1f1238dff4de420e47566b2c 已修复。

另，Rime 切换方案的时候，如果 A 方案有选项 a、B 方案没有，则 lua 不会自动刷新选项 a。遇到这种情况，如果有问题再部署一下就能好。
