### ISSUE TITLE
简码三顶时sss+Tab行为异常

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#11]
声笔简码在三顶状态时，sss+Tab行为发生异常，被Tab转换为ss's_，而不是ss_s_，其中_表示空格。估计是由于声声词编码由ss+下划线变为ss'后造成的。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/0d554e9e9693d28f1f1238dff4de420e47566b2c 已修复
