### ISSUE TITLE
声笔自然造词和选择错误

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#16]
20240213版，用「冷静」「点」造词后，导出来发现有ljdm和ljdmoe两条临时词组，同时在输入ljdm和ljdmoe后都会出现「冷静点」这个临时词组，而且均排在首选，导致选择重码时错位，用e选择的是u位的重码。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/8675d298b6ff003044d28cb0699b5b64abdb1657 已修复
