### ISSUE TITLE
Shift+Tab在fcitx5-rime不工作

### ISSUE THREAD

**Issue by diannajonesa** [sbsrf/sbsrf#17]
fcitx5下将Shift+Tab识别为Shift+ISO_Left_Tab
加入
    - { when: paging, accept: Shift+ISO_Left_Tab, send: Page_Up }
    - { when: has_menu, accept: Shift+ISO_Left_Tab, send_sequence: "{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}" }
后才可以使用

**Comment by followfateg** [comment]
手机上fcitx5吗？

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/7fc638ef4ff0eec178bb337e388698b14fe84ff0 解决
