### ISSUE TITLE
窗口切换时提示和输入异常

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#21]
用户「火星地区多奇葩」反映的问题。

可能还有一个问题是窗口切换，比如我在百度搜索那里打几个字，回到QQ打几个字，再切回百度搜索，他的自动调频就失灵了。

QQ窗口好了之后，最后定在活跃的，后面去百度搜索窗口，一直换选项，还是活跃的，等于自动调频失灵了。

一开始从百度搜索转到QQ窗口，前面几个一样自动调频不了，后面第四个到活跃的，他就好了，可是换百度窗口，还是失灵了，这样对于需要切换窗口的话，可能会有影响，除非一直不换窗口。

每次有问题都重新部署吗，我知道部署一遍就好了，可是每次切换一次窗口就要重新部署一遍，也太麻烦了吧，如果要换10次窗口，不得部署十次。

提建议是看看能不能解决问题，如果问题无法解决，那就尽量不换窗口，或者部署，如果能解决，还是看看怎么解决才是吧。

对了，可能自造词也会有影响。确实自造词有问题。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/b10b6249e89176615f3eb92769e15258478d4aae 已修复
