### ISSUE TITLE
飞码飞讯有时造词失败

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#26]
比如，用「后天」「白天」造「后天白天」就会失败。

**Comment by tansongchen** [comment]
白天（bute）是一个声笔声笔词，在 auto_length.lua 中是作为组合码出现的，并没有用 Phrase 来封装，所以没有触发上屏的回调函数

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/b8542cda2426d7a4c84ebf9c7e27e49e82aec6b3 修复
