### ISSUE TITLE
飞码词组翻页选择时不对

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#27]
用小狼毫，打完四码，翻页选择第二页的重码，仍然选择的是首页的选项，而且不会上屏。这是以前曾经出现过的，后来解决了。现在又出现了。

后来发现这个问题不总是出现，应该和窗口切换的问题相关。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/b10b6249e89176615f3eb92769e15258478d4aae 应该已修复
