### ISSUE TITLE
选择提示错误

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#28]
复现方法：在Weasel或者Squirrel上，分别打开两个应用，在其中一个中用声笔拼音，另一个中用声笔飞码，在输入一半时进行切换输入，会出现在声笔拼音中出现aeuio选择提示，或者在声笔飞码中出现23789提示的怪现象。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/b10b6249e89176615f3eb92769e15258478d4aae 已经解决
