### ISSUE TITLE
声笔全系列单字正码统一到通规8105字

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#31]
声笔全系列单字正码统一到通规8105字，补齐缺失的通规字，去掉通规以外的字。通规以外的字，只用字海两分查字来支持。

**Comment by tansongchen** [comment]
通规本身也有歧义，比如说磺酸的「磺」就不是通规字。建议还是保留一些通规之外的常用字，不然可能给用户造成困扰。

**Comment by sbxlm** [comment]
算了，那还是保留GBK字集吧，已经做了大量的工作，不然太浪费了。仅仅是声笔拼音弄成8105也没关系。

**Comment by tansongchen** [comment]
声笔拼音加到 gbk 也没有技术问题，只不过目前试验期间还没有做
