### ISSUE TITLE
顶功处理器支持逻辑表达式

### ISSUE THREAD

**Issue by sbxlmdsl** [sbsrf/sbsrf#34]
希望顶功处理器支持逻辑表达式。目前单一的when和when_not条件功能太弱，不少逻辑关系难以简单明了地表达，甚至无法表达。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/45c522439a35742ef74dd13e7ab82a4988cd0029 通过加入顶功 strategy 允许短路求值，从而支持了飞讯的增强慢顶模式中数字的四二顶。短路求值之后，逻辑也得到了大大的简化，不需要在 sbxlm.yaml 中考虑飞讯的状态了
