### ISSUE TITLE
Lua版声笔还欠缺的特征

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#37]
1. enable_filtering: 多字词筛选
2. forced_selection: 强制选重
3. single_selection: 单次选重

**Comment by tansongchen** [comment]
`enable_filtering` 是有的

<img width="185" alt="image" src="https://github.com/sbsrf/sbsrf/assets/31927845/42dd148d-f095-49c6-b717-88e06b8cc4e8">

**Comment by tansongchen** [comment]
`forced_selection` 和 `enable_filtering` 完整支持了，但是 `single_selection` 有必要吗，我看教程上也没写，应该没有几个人用

**Comment by sbxlm** [comment]
> `forced_selection` 和 `enable_filtering` 完整支持了，但是 `single_selection` 有必要吗，我看教程上也没写，应该没有几个人用

single_selection是为了兼容类似星空系列的方式，用的人确实少，不支持也行了。
