### ISSUE TITLE
对飞系声声词的一些想法

### ISSUE THREAD

**Issue by Wit-2k** [sbsrf/sbsrf#43]
目前的声声词一定程度上降低了组合变换的必要性，如「不要」「不怕」「出来」「发生」等，考虑到它们确实常用，大家也能认可。但二简字+一简字的组合不可能有重码，故像「但是」「过去」「开发」「客人」「看出」「统一」之类的词可以修改为其他需要szsz才能打出的词，如这几个例子可分别改为「多少」「感情」「开放」「宽容」「开车」「同意」。当然，一些确实常用的如「客人」「老人」「头发」「也是」可以不改。

另外，wp对应的「无派」实在有些费解，不如改成「外婆」，同时取消wpo这一编码，再加一个wpu的编码对应「网盘」，如此则显得合理许多。

飞码目前不能提示缩减码，故打字时常常用不到声声词，故设计的声声词必须尽可能常用（在各种场景下的综合使用频率较高），使得用户有动力专门记忆。

**Comment by tansongchen** [comment]
声声词不光是飞码在用，简码也在用同样一套，所以过滤那些可以组合变换打出来的词也不能过于激进。

自定义只需要编辑 sbf.dict.yaml 即可，这个文件一上来就是声声词，很直观

**Comment by sbxlmdsl** [comment]
wp编「无派」，这个确实不合理，可以改为「外婆」

**Comment by sbxlm** [comment]
「无派」改为「物品」，「北京」改为「不仅」，其它词做相应调整。其它方案也做类似调整。
