### ISSUE TITLE
声笔简码造词优化

### ISSUE THREAD

**Issue by sbxlmdsl** [sbsrf/sbsrf#47]
当码长大于等于5时，按单引号，则自动把4码后的笔画编码移动到首码后，然后将光标定位到其后，以便衔接造词过程，不浪费已经输入的编码。

**Comment by sbxlm** [comment]
还可以进一步考虑尽量减少手动定位。

**Comment by sbxlm** [comment]
似乎可以用TableTranslator模拟出ScriptTanslator的效果，同时具有更好的可控性和更高的运行效率。
