### ISSUE TITLE
U引导不支持选重

### ISSUE THREAD

**Issue by Hxdqdqp** [sbsrf/sbsrf#48]
U引导的自定义词库之前还能支持aeuio选重，现在不支持选重了，连选重都不行的话，那就只能用方向键选了。

那这样这个自定义词库反而变得更难用了。

希望可以加入选重功能。

**Comment by sbxlm** [comment]
这个u引导的自定义词库主要目的是解决带字母、符号等词组的输入问题，只要保证编码唯一，也就不存在选重的问题了。默认的几个示例词组就是这么来定义的。如果需要方便的选重，就用方案专用的自定义词典吧。

**Comment by Hxdqdqp** [comment]
好吧

**Comment by tansongchen** [comment]
这个 sbzdy 本来就不是为了大量定义编码来做的，如果有重码，可以加码来处理，比如示例中的

<img width="1101" alt="image" src="https://github.com/sbsrf/sbsrf/assets/31927845/fac60275-83bc-49d1-8675-9cf93d0b2586">

**Comment by tansongchen** [comment]
主要的困难在于，如果要支持 aeiou 选重，编码就不能含有 aeiou，这对用户自定义特殊编码并不是很方便

**Comment by Hxdqdqp** [comment]
好的，其实如果是编码可以含有aeiou，那么自定义词库说明应该可以改下。

因为上面写的是接aeuio以外的小写字母和数字，所以我以为是aeiou不能设置。

如果可以设置的话，那也可以吧。

还有，我试验了下，后面加数字可以做到类似选重的情况，不过只能加10个，因为重复的数字不能用。

然后也能添加aeiou用来选重，效果也是一样的，支持延迟什么的。

唯一不足的地方就在于不能设置更多内容，不过这个本来就是用来设置一些不常用的自造词，也够用了
