### ISSUE TITLE
sbzdy问题

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#49]
通用自定义词典，在去掉编码中的u，采用类似a引导拼音的方式后，输入时出现不需要的声声词等。字词型方案会有这个问题，整句型方案没有。

![QQ截图20240310120608](https://github.com/sbsrf/sbsrf/assets/6541069/7c5acf93-6b84-416a-8bc4-ba94e5759027)

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/d1bb77fc6d2953a3fe8996c5180033a8ee619796 已解决
