### ISSUE TITLE
基本码翻页后选重不正常

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#5]
基本码翻页后选重仍然选择的是首页的选项。

**Comment by sbxlm** [comment]
已经解决

**Comment by sbxlm** [comment]
不行，问题还是存在。

**Comment by tansongchen** [comment]
https://github.com/sbsrf/sbsrf/commit/69087f653402ece5bbfef0a136dcc4676bea98c0 已解决
