### ISSUE TITLE
声笔简拼单引号定位失效

### ISSUE THREAD

**Issue by sbxlm** [sbsrf/sbsrf#69]
声笔简拼在长词联想时，若首选为5字及以上词，那么单引号定位就失效，没有如何作用。同时，发现直接用Shift+Right也没有作用。估计是上游librime的bug导致的。

![QQ截图20240519085955](https://github.com/sbsrf/sbsrf/assets/6541069/fed0d5e2-a17f-4ede-90e3-8184a5d25a22)

**Comment by sbxlmdsl** [comment]
最后发现是因为postpone.lua没考虑到长词而造成的。
