### ISSUE TITLE
双拼方案的一个新特性设想

### ISSUE THREAD

**Issue by Wit-2k** [sbsrf/sbsrf#70]
### 问题
双拼方案输入多字词的方法是sssy，只有最后一个韵母能够减少重码，会出现两种情况：①要连续翻页才能找到；②自动调频在遇到连续出现的相同编码的词会造成一定的干扰。又因为双拼方案在21个声母键上安排了韵母，输入sssy实际上还可能是sysy，故候选项从二字词到四字词都有，有时会对连续输入造成一定的负面影响。

### 设想
因此，我猜想能否找到一种方法限定候选项的字数。毕竟，自动调频多数时候好用，但总存在一些场景需要打不少的非常见词组。以下给出两种方案供开发者大大参考：
1. 取消数字顶屏，改为限定字数。如输入srfa3，候选不会出现“算法”一项；输入mksy5，候选只剩下“马克思主义”和“魔卡少女樱”两项。但也存在一些特殊的情况，如jsqi的候选全是三字词，故还应保留词组的扩展编码，如输入jyxy3ei后，应只有“基因型”“教育性”“均匀性“”节约型“”均一性””教育兴“这几个候选项。为了照顾用户的习惯，应当设计两种选重输入顺序任意，即上例还应允许用户输入jyxyei3。
2. 用反单引号\`和反斜杠\，取消对应顶屏。
- 对于真sssy（前两个编码无法成字，如wm），默认只显示三字词，用户可接着输入反单引号\`后接aeiou对应不同字数的候选项，如a对应四字词，e对应五字词，i对应六字词，o对应七字词，u对应八字及以上的词。若对应字数的词不存在或未收录，则依然只显示三字词，但输入框显示两个反单引号\`\`提示用户，此时用户需要重新输入\`后接aeiou。
- 对于伪sssy（前两个编码可以成字，如bc），依然默认只显示三字词，用户可接着输入\以过滤出二字词，也可以输入`后接aeiou，其他同真sssy。

这两种方案各有千秋。但因为数字键不好按，我个人更倾向于第二种方案，同样的，它也需要保留词组的扩展编码，故最理想的情况是用户输入\`后可以在输入框看到\`，接着输入aeiou后输入框只保留sssy，不显示\`和aeiou，候选项的字数全部一致，用户可接着输入扩展编码限定首字。

希望开发者大大能看到我的建议，虽然这又意味着更多的工作量了哈哈，但愿万能的Rime能实现我的想法。

**Comment by Wit-2k** [comment]
方案二也应允许任意顺序，即允许sssybb`(aeiou)这样的输入

**Comment by sbxlmdsl** [comment]
四码重码重灾区的问题已经考虑到了，可以通过扩展编码来解决，即追加首字的前两笔即可。
